name: season_spot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # firebase
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2

  # utilities
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: "^0.13.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700

  uses-material-design: true

scripts:
  gen:
    icon: "dart run flutter_launcher_icons -f launcher_icon.yaml"
    splash: "dart run flutter_native_splash:create --path=native_splash.yaml"
